spring:
    ai:
        google:
            genai:
                api-key: ${GEMINI_API_KEY}
                chat:
                    options:
                        model: gemini-2.5-flash
                embedding:
                    api-key: ${GEMINI_API_KEY}
                    text:
                        options:
                            dimensions: 768
                            model: gemini-embedding-001

        vectorstore:
            pgvector:
                initialize-schema: true
                #        remove-existing-vector-store-table: true
                index-type: HNSW
                distance-type: COSINE_DISTANCE
                dimensions: 768

    #  datasource:
    #    url: jdbc:postgresql://localhost:5432/garment_erp_db
    #    username: postgres
    #    password: postgres
    #    driver-class-name: org.postgresql.Driver

    cache:
        type: caffeine
        caffeine:
            spec: expireAfterWrite=5m

    datasource:
        url: ${NEON_DB_URL}
        username: ${NEON_DB_USERNAME}
        password: ${NEON_DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
